services:
  invoice_ocr:
    image: invoice_ocr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice_ocr
    restart: always
    env_file:
      - .env
    networks:
      - web
    dns:
      - 223.5.5.5
      - 114.114.114.114
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_PASSWORD=Gmcc@123
      - DB_USER=root
      - DB_NAME=invoice_db
      - LLM_MODEL_NAME=hunyuan-vision
    volumes:
      - ../logs/invoice:/app/logs
